// <auto-generated />
namespace BetweenFriends.Migrations.BFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201802272126139_fixTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
